[project]
name = "bf-nowcasting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.0",
    "joblib>=1.5.1",
    "pandas>=2.3.1",
    "scikit-learn==1.4.2",
    "seaborn>=0.13.2",
    "xgboost>=3.0.2",
]
